sudo: required
dist: trusty
group: deprecated-2017Q4
language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - CURPATH=$(pwd)
    - ACEDIR=$HOME/Tools
    - ACE_ROOT=$ACEDIR/ACE_wrappers
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7

before_install:
  - mkdir -p $ACEDIR
  - cd $ACEDIR
  - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.tar.gz
  - tar zxf ACE-6.4.0.tar.gz

before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; 
      echo -e "#define ACE_HAS_EVENT_POLL" >> $ACE_ROOT/ace/config.h; 
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      else
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      fi
    fi

  - cd $ACE_ROOT
  - $ACE_ROOT/bin/mwc.pl -type gnuace ACE.mwc
  - make ACE > /dev/null 2>&1
  - ls $ACE_ROOT/lib/
#
# Build Matrix
#
matrix:
  include:

  #
  # Build and scan
  #
  - os: linux
    env:
      - secure: "QI2lF2Fr299l+N+vcA86wXiIEa71B7iWgCaafHSNvXJ9OI/S5Nsz4lW3qLMre/IQ3dpo/oRETwZ/Xkqu1t508BasqS0mYlanZqBT1hq9lDwRohzypyH6EDCMZ2ElAhiDPtnayoz9xsHQgLgJUEe+6FOWRMd5jLkAHU+Oro7Y9MMChNSW20wgDW27sJTLQn5/VjfEFdT2LmsqkD+J5hgpBaSeg5TTL/p19AmNVMWsn77DmA6yoDIWUWUE9uZtMfBeDofIYwXc/4SkQHauR466qDhFBfPwTTWjGKGsbbkHeFmbCAPY3bv6dCSU2ZA6Xa/3xPApYDyZoq/Me+3ahVBwyWDtzyhOchU2J4Avlupe6ggxEnESiMqzHtZ/+sytAE8lS1uuWVTS0SsfV2xcAbUWq2ZmcZYBxSPdFqdLhHCSIy29LWY31WtBHs0VwzynC6Dz6TIbbUt/4Fbi1cYUUyJ7+LMUEBiC9jodE8zj/zTe0nhAwUn7GR6jD0lyOChy1eJspXatWVVA/KmN4q3bkOrowrRN4YCiDA1kNgNv6pxQej6rpftpqTfBTIVY7AK4c6d5V0cgIMa4RQyuspvPvvqlE2a0T3Sb7oDB88R7cPB3LMjVid7xdI9iil4/WOygiZqm9Na7S1j2yRmpatrPMD3Xg4AE9PMTELJQYCwS0m8SfcE="
    script: 
      - export
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then 
          cd $TRAVIS_BUILD_DIR/purenessscopeserver/purenessscopeserver/PurenessScopeServer/Linux_Bin;
          $ACE_ROOT/bin/mwc.pl -type gnuace pss.mwc;
          make -j 4;
        fi

    addons:
      coverity_scan:
        project:
          name: "freeeyes/PSS"
          description: "Build submitted via Travis CI"
        notification_email: freeeyes@163.com;liuchao412@foxmail.com
        build_command_prepend: "cd $TRAVIS_BUILD_DIR/purenessscopeserver/purenessscopeserver/PurenessScopeServer/Linux_Bin;$ACE_ROOT/bin/mwc.pl -type gnuace pss.mwc;make clean"
        build_command: "make -j 4"
        branch_pattern: master

  #
  # Update Report
  #
  - os: linux
    env:
      - GH_REF: github.com/freeeyes/PSS.git
      - secure: "Tqz9j2VlU+mJgCcnceaam/X/N8cgQa+O92qeGUFOKGAqJkxiKHQAPnqj7+YmgCAKVEbBEMPo08Putcro00YQKElkrWpuUc2J49+DYzd8ZoSXgUEOPuYwTzPSIcSCN1cKogjBuTxJrp5WbmRAiH6gIhB+m4r2ToCGnZ6MXnkVGracjRaPoqLC4j3S5FXuq/Ilp2ZW9SqRQiy+yGQzW7UvbyE0LRhoXb/ptFFMgW/NomoUlOIyCFSqXfPMxQsHFGD4ifcjl8pGWGE5OB0Sm9IMbe9/DOL11ouSPy/0OevPH23VuYmiIz+acVa7A48Dm1Z5sFsHvyFAiU5tiXCVS7VTCqxL4M4Ac1NlpDDMngwkms0w4M9J9TXNzNA958glhfBoMaIWcHMpZ0hEdWrulAKIrBZnevm0yMvTfnxmyA4Pie98UFrAlljZXiUTZtrHGC2Z1oSJZ92sOfc5uDyA1lZMf7XiLN9HbCHBZtKdo5PS2PhF97oOTZdOvpRKkwgMb+sqfVM/JGsdsS8eSmkIyCB0JkDjJKWuA7q8f3xDlPyigjUtFXkllEa8eyYsRFdoLYIK/vLWo+/J7PoICxCdXUnC3YmcXkGaisQxnjgAyhnEnG8z38Ra2uDh2W7ltLfgEtaAChYp6UZMR4XboM7F1DzB2zFSociUJ61tn4fibIzPGOg="
    script:
      - export
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/purenessscopeserver/PacketParse_Interface
      - $ACE_ROOT/bin/mwc.pl -type gnuace
      - make -j 4
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/purenessscopeserver/example-Module/TcpTest
      - $ACE_ROOT/bin/mwc.pl -type gnuace
      - make -j 4
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/purenessscopeserver/PurenessScopeServer/Linux_Bin
      - $ACE_ROOT/bin/mwc.pl -type gnuace
      - make -j 4
      - ./PurenessScopeServer > /dev/null 2>&1 &
      - sleep 10
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/Test
      - make -j 4
      - ./Test_Pss
      - killall -9 PurenessScopeServer
      - cd $TRAVIS_BUILD_DIR
      - git init
      - git config user.name "freeeyes"
      - git config user.email "freeeyes@163.com"
      - git add -u ./testresult/result.md
      - git commit -m "[ci skip]Travis CI Update result.md"
      - git push -f "https://${GH_TOKEN}@${GH_REF}" HEAD:master
